controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    soft_brush_controller:
      type: velocity_controllers/JointVelocityController

    hard_brush_controller:
      type: velocity_controllers/JointVelocityController

soft_brush_controller:
  ros__parameters:
    joints:
      - soft_brush_joint
    interface_name: velocity

hard_brush_controller:
  ros__parameters:
    joints:
      - hard_brush_joint
    interface_name: velocity

